apiVersion: v1
kind: Service
metadata:
  name: wordpress-50-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-5.0
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-5.0
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-5.0-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-5.0
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-5.0
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-54-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-5.4
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-5.4
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-5.4-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-5.4
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-5.4
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-55-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-5.5
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-5.5
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-5.5-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-5.5
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-5.5
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-56-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-5.6
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-5.6
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-5.6-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-5.6
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-5.6
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-57-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-5.7
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-5.7
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-5.7-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-5.7
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-5.7
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-58-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-5.8
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-5.8
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-5.8-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-5.8
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-5.8
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-59-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-5.9
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-5.9
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-5.9-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-5.9
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-5.9
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-60-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-6.0
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-6.0
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-6.0-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-6.0
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-6.0
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-61-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress-6.1
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-6.1
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-6.1-mysql
  namespace: qa-wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-6.1
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-6.1
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        resources:
          requests:
            cpu: "450m"
            memory: "450Mi"
          limits:
            cpu: "650m"
            memory: "750Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
