services:
  _defaults: { public: true }

  Wordlift\Modules\Include_Exclude\Plugin_Enabled:
    class: Wordlift\Modules\Include_Exclude\Plugin_Enabled
  Wordlift\Modules\Include_Exclude\Admin\Settings:
    class: Wordlift\Modules\Include_Exclude\Admin\Settings
  Wordlift\Modules\Include_Exclude\API:
    class: Wordlift\Modules\Include_Exclude\API