name: docker_build_and_k8s_deployment

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        WP-ver: [wlp-wp-5.0, wlp-wp-5.4, wlp-wp-5.5, wlp-wp-5.6, wlp-wp-5.7, wlp-wp-5.8, wlp-wp-5.9, wlp-wp-6.0, wlp-wp-6.1]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push wp-4.4
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          context: .
          file: ./Dockerfile
          push: true
          target: ${{ matrix.WP-ver }}
          username: ${{ secrets.username }}
          password: ${{ secrets.PAT }}
          repository: wordlift/${{ matrix.WP-ver }}
          tags: latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
      # Set the target AKS cluster.
    environment:
      name: QA-environment
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change as needed
          
      - name: delete old deployment
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "v1.23.6"
        with:
          args: delete -f manifests/wordpress-deployment.yml,manifests/wordpress-mysql-deployment.yml --ignore-not-found=true

      - name: Deploy new package
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "v1.23.6"
        with:
          args: apply -f manifests/wordpress-deployment.yml,manifests/wordpress-mysql-deployment.yml,manifests/wordpress-ingress.yml
